import pg from "pg";
import crypto from "crypto";
const { Pool } = pg;
const pool = globalThis.__nroraPaymentsPool || new Pool({ connectionString: process.env.DATABASE_URL, max: 5, idleTimeoutMillis: 10000, connectionTimeoutMillis: 10000 });
globalThis.__nroraPaymentsPool = pool;
const cleanEnv=v=>String(v??"").trim().replace(/^['\"]|['\"]$/g,"").trim();
const SECRET=cleanEnv(process.env.SESSION_SECRET)||"change-this-session-secret-in-vercel";
const RAZORPAY_KEY_ID=cleanEnv(process.env.RAZORPAY_KEY_ID);
const RAZORPAY_KEY_SECRET=cleanEnv(process.env.RAZORPAY_KEY_SECRET);
const VERIFY_WAIT_MINUTES=10;
const json=(res,status,body)=>res.status(status).json(body);
const readToken=t=>{try{const [p,s]=String(t||"").split(".");const u=JSON.parse(Buffer.from(p,"base64url").toString());const e=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))||u.exp<Date.now())return null;return u}catch{return null}};
const requireAuth=(req,res)=>{const t=(req.headers.authorization||"").replace(/^Bearer\s+/i,"");const u=readToken(t);if(!u||!["admin","division_manager","area_manager","tl","staff"].includes(u.role)){json(res,401,{error:"Unauthorized"});return null}return u};
async function razor(path,method="GET",body){if(!RAZORPAY_KEY_ID||!RAZORPAY_KEY_SECRET)throw new Error("Razorpay credentials are missing in Vercel Production.");const auth=Buffer.from(`${RAZORPAY_KEY_ID}:${RAZORPAY_KEY_SECRET}`).toString("base64");const r=await fetch(`https://api.razorpay.com/v1${path}`,{method,headers:{Authorization:`Basic ${auth}`,"Content-Type":"application/json"},body:body?JSON.stringify(body):undefined});const data=await r.json().catch(()=>({}));if(!r.ok){const requestId=r.headers.get("x-razorpay-request-id")||r.headers.get("x-request-id")||"";if(r.status===401){const secretFp=crypto.createHash("sha256").update(RAZORPAY_KEY_SECRET).digest("hex").slice(0,12);throw new Error(`Razorpay rejected Production credentials (HTTP 401). Key=${RAZORPAY_KEY_ID.slice(0,18)}… Secret fingerprint=${secretFp}.${requestId?` Request ID=${requestId}`:""}`);}throw new Error(data?.error?.description||data?.error?.code||`Razorpay request failed (HTTP ${r.status})${requestId?` Request ID=${requestId}`:""}`)}return data;}
async function schema(){await pool.query("alter table payments add column if not exists status varchar(30) not null default 'pending'");await pool.query("alter table payments add column if not exists gateway_order_id varchar(120) default ''");await pool.query("alter table payments add column if not exists gateway_payment_id varchar(120) default ''");await pool.query("alter table payments add column if not exists qr_code_id varchar(120) default ''");await pool.query("alter table payments add column if not exists verification_started_at timestamptz");await pool.query("alter table payments add column if not exists verification_ready_at timestamptz");await pool.query("create unique index if not exists payments_gateway_order_idx on payments(gateway_order_id) where gateway_order_id <> ''");await pool.query("create unique index if not exists payments_gateway_payment_idx on payments(gateway_payment_id) where gateway_payment_id <> ''");await pool.query("create unique index if not exists payments_qr_code_idx on payments(qr_code_id) where qr_code_id <> ''");}
async function receipt(customerId,paymentId){const old=await pool.query("select * from receipts where payment_id=$1 limit 1",[paymentId]);if(old.rowCount)return old.rows[0];const no="NR-"+new Date().getFullYear()+"-"+crypto.randomBytes(4).toString("hex").toUpperCase();const r=await pool.query("insert into receipts(customer_id,payment_id,receipt_no) values($1,$2,$3) returning *",[customerId,paymentId,no]);return r.rows[0];}
async function activateMembership(customerId,amount){const existing=await pool.query("select * from memberships where customer_id=$1 and renewal_date>=current_date order by id desc limit 1",[customerId]);if(existing.rowCount)return existing.rows[0];const r=await pool.query("insert into memberships(customer_id,amount,renewal_date) values($1,$2,(current_date + interval '1 year')::date) returning *",[customerId,amount]);return r.rows[0];}
async function markVerificationPending(paymentRow,paymentId,method){const u=await pool.query("update payments set status='verification_pending',gateway_payment_id=$1,transaction_ref=$2,method=$3,paid_at=now(),verification_started_at=coalesce(verification_started_at,now()),verification_ready_at=coalesce(verification_ready_at,now()+interval '10 minutes') where id=$4 and status not in ('captured','failed') returning *",[paymentId,paymentId,String(method||"UPI").toUpperCase(),paymentRow.id]);return u.rows[0]||paymentRow;}
async function finalizeIfReady(paymentRow){const readyAt=paymentRow.verification_ready_at?new Date(paymentRow.verification_ready_at).getTime():0;if(paymentRow.status==="captured"){return {payment:paymentRow,receipt:await receipt(paymentRow.customer_id,paymentRow.id),membership:await activateMembership(paymentRow.customer_id,Number(paymentRow.amount))};}if(paymentRow.status!=="verification_pending"||!readyAt||Date.now()<readyAt)return null;let confirmed=null;if(paymentRow.gateway_payment_id){try{confirmed=await razor(`/payments/${encodeURIComponent(paymentRow.gateway_payment_id)}`)}catch(e){console.error("Payment recheck failed",e)}}if(!confirmed&&paymentRow.gateway_order_id){try{const order=await razor(`/orders/${encodeURIComponent(paymentRow.gateway_order_id)}`);if(order.status==="paid")confirmed={status:"captured",amount:order.amount}}catch(e){console.error("Order recheck failed",e)}}if(!confirmed||confirmed.status!=="captured"||Number(confirmed.amount)/100!==Number(paymentRow.amount))return null;const u=await pool.query("update payments set status='captured' where id=$1 and status='verification_pending' returning *",[paymentRow.id]);const p=u.rows[0]||paymentRow;return {payment:p,receipt:await receipt(p.customer_id,p.id),membership:await activateMembership(p.customer_id,Number(p.amount))};}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(req.method==="OPTIONS")return res.status(204).end();try{const u=requireAuth(req,res);if(!u)return;await schema();let path=req.query?.path;if(Array.isArray(path))path=path.join("/");else path=String(path||"");path=path.replace(/^\/+|\/+$/g,"");if(req.method==="POST"&&path==="create-order"){const customerId=Number(req.body?.customer_id);if(!customerId)return json(res,400,{error:"customer_id is required"});const c=await pool.query("select id,name,phone,vehicle_no from customers where id=$1",[customerId]);if(!c.rowCount)return json(res,404,{error:"Customer not found"});const customer=c.rows[0];const order=await razor("/orders","POST",{amount:450000,currency:"INR",receipt:`NRORA-${customerId}-${Date.now()}`,payment_capture:1,notes:{customer_id:String(customerId),customer_name:customer.name,vehicle_no:customer.vehicle_no}});const p=await pool.query("insert into payments(customer_id,amount,method,transaction_ref,status,gateway_order_id) values($1,4500,'UPI','', 'pending',$2) returning *",[customerId,order.id]);let qr=null,qrError="";try{qr=await razor("/payments/qr_codes","POST",{type:"upi_qr",name:`NRORA-${customerId}`,usage:"single_use",fixed_amount:true,payment_amount:450000,description:"NRORA Yearly Road Assistance Membership",notes:{customer_id:String(customerId),payment_id:String(p.rows[0].id),vehicle_no:String(customer.vehicle_no||"")}});await pool.query("update payments set qr_code_id=$1 where id=$2",[qr.id,p.rows[0].id])}catch(e){qrError=e?.message||"QR generation failed"}return json(res,201,{orderId:order.id,keyId:RAZORPAY_KEY_ID,amount:450000,currency:"INR",paymentId:p.rows[0].id,customer,qr:qr?{id:qr.id,image_url:qr.image_url,image_content:qr.image_content,status:qr.status,close_by:qr.close_by}:null,qrError});}
if(req.method==="POST"&&path==="verify"){const {razorpay_order_id,razorpay_payment_id,razorpay_signature}=req.body||{};if(!razorpay_order_id||!razorpay_payment_id||!razorpay_signature)return json(res,400,{error:"Incomplete payment verification data"});const expected=crypto.createHmac("sha256",RAZORPAY_KEY_SECRET).update(`${razorpay_order_id}|${razorpay_payment_id}`).digest("hex");if(expected!==razorpay_signature)return json(res,400,{error:"Payment signature verification failed"});const p=await razor(`/payments/${encodeURIComponent(razorpay_payment_id)}`);if(p.status!=="captured")return json(res,409,{error:`Payment is ${p.status}. We will activate after bank/gateway confirmation.`});const q=await pool.query("select * from payments where gateway_order_id=$1 limit 1",[razorpay_order_id]);if(!q.rowCount)return json(res,404,{error:"Payment record not found"});const row=await markVerificationPending(q.rows[0],razorpay_payment_id,p.method);return json(res,202,{ok:true,status:row.status,payment:row,verificationReadyAt:row.verification_ready_at,waitMinutes:VERIFY_WAIT_MINUTES,message:"Payment received. Bank/gateway verification is in progress. Membership will activate automatically after confirmation."});}
if(req.method==="GET"&&path==="status"){const orderId=String(req.query?.order_id||"");if(!orderId)return json(res,400,{error:"order_id is required"});const r=await pool.query("select p.*,c.name customer_name,c.phone,c.vehicle_no,r.receipt_no,r.created_at receipt_created_at,m.renewal_date from payments p left join customers c on c.id=p.customer_id left join receipts r on r.payment_id=p.id left join memberships m on m.customer_id=p.customer_id and m.renewal_date>=current_date where p.gateway_order_id=$1 order by m.created_at desc limit 1",[orderId]);if(!r.rowCount)return json(res,404,{error:"Payment not found"});let row=r.rows[0];if(row.status==="pending"&&row.qr_code_id){try{const qrPayments=await razor(`/payments/qr_codes/${encodeURIComponent(row.qr_code_id)}/payments?count=10`);const qp=(qrPayments.items||[]).find(x=>x.status==="captured"&&Number(x.amount)===Number(row.amount)*100);if(qp)row=await markVerificationPending(row,qp.id,qp.method)||row}catch(e){console.error("QR status check failed",e)}}const done=await finalizeIfReady(row);if(done)return json(res,200,{...done.payment,customer_name:row.customer_name,phone:row.phone,vehicle_no:row.vehicle_no,receipt_no:done.receipt.receipt_no,receipt_created_at:done.receipt.created_at,renewal_date:done.membership.renewal_date,verification_status:"confirmed",message:"Payment confirmed. Membership activated."});if(row.status==="verification_pending")return json(res,200,{...row,verification_status:"pending",message:"Payment received. Bank/gateway verification is in progress.",waitMinutes:VERIFY_WAIT_MINUTES});return json(res,200,row);}return json(res,404,{error:"Not found"});}catch(e){console.error(e);return json(res,500,{error:e?.message||"Internal server error"})}}
