import pg from "pg";
import crypto from "crypto";
const { Pool } = pg;
const pool = globalThis.__nroraPool || new Pool({ connectionString: process.env.DATABASE_URL, max: 5, idleTimeoutMillis: 10000 });
globalThis.__nroraPool = pool;
const SECRET = process.env.SESSION_SECRET || "change-this-session-secret-in-vercel";
const ADMIN_USERNAME = process.env.ADMIN_USERNAME || "admin";
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD || "NRORA@123";
const ROLES=["admin","division_manager","area_manager","tl","staff","customer","mechanic"];
const json=(res,status,body)=>res.status(status).json(body);
const hash=p=>crypto.createHash("sha256").update(`${SECRET}:${p}`).digest("hex");
const token=u=>Buffer.from(JSON.stringify({id:u.id,username:u.username,role:u.role,exp:Date.now()+30*24*60*60*1000})).toString("base64url")+"."+crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");
const readToken=t=>{try{const[p,s]=t.split(".");const u=JSON.parse(Buffer.from(p,"base64url").toString());const e=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))||u.exp<Date.now())return null;return u}catch{return null}};
const userFrom=req=>{const t=(req.headers.authorization||"").replace(/^Bearer\s+/i,"");return t?readToken(t):null};
const requireAuth=(req,res,roles=[])=>{const u=userFrom(req);if(!u||(roles.length&&!roles.includes(u.role))){json(res,401,{error:"Unauthorized"});return null}return u};
async function schema(){await pool.query(`create table if not exists customers(id bigserial primary key,name varchar(120) not null,phone varchar(20) not null,address text default '',vehicle_no varchar(30) not null,created_at timestamptz default now());
create table if not exists technicians(id bigserial primary key,name varchar(120) not null,phone varchar(20) not null,specialization varchar(120) default '',active boolean default true,created_at timestamptz default now());
create table if not exists service_requests(id bigserial primary key,customer_id bigint references customers(id) on delete set null,status varchar(30) default 'pending',location text default '',description text default '',assigned_technician varchar(120) default '',created_at timestamptz default now());
create table if not exists mechanic_orders(id bigserial primary key,request_id bigint unique references service_requests(id) on delete cascade,technician_id bigint references technicians(id) on delete set null,technician_name varchar(120) default '',status varchar(30) default 'sent',assigned_by bigint,created_at timestamptz default now(),accepted_at timestamptz,started_at timestamptz,completed_at timestamptz);
create table if not exists payments(id bigserial primary key,customer_id bigint references customers(id) on delete set null,amount numeric(12,2) not null default 4500,method varchar(30) default 'UPI',transaction_ref varchar(120) default '',paid_at timestamptz default now());
create table if not exists memberships(id bigserial primary key,customer_id bigint references customers(id) on delete cascade,amount numeric(12,2) not null default 4500,renewal_date date not null,created_at timestamptz default now());
create table if not exists receipts(id bigserial primary key,customer_id bigint references customers(id) on delete set null,payment_id bigint references payments(id) on delete set null,receipt_no varchar(50) unique not null,created_at timestamptz default now());
create table if not exists users(id bigserial primary key,username varchar(80) unique not null,password_hash text not null,role varchar(30) not null default 'staff',name varchar(120) not null,phone varchar(20) default '',active boolean default true,created_at timestamptz default now());
create table if not exists customer_update_requests(id bigserial primary key,customer_id bigint references customers(id) on delete cascade,requested_by bigint references users(id),changes jsonb not null,status varchar(20) default 'pending',reviewed_by bigint references users(id),reviewed_at timestamptz,created_at timestamptz default now());`);const r=await pool.query("select id from users where username=$1",[ADMIN_USERNAME]);if(!r.rowCount)await pool.query("insert into users(username,password_hash,role,name) values($1,$2,'admin',$3)",[ADMIN_USERNAME,hash(ADMIN_PASSWORD),"NRORA Admin"]);}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,PATCH,DELETE,OPTIONS");if(req.method==="OPTIONS")return res.status(204).end();try{await schema();let path=req.query?.path;if(Array.isArray(path))path=path.join("/");else path=String(path||"");path=path.replace(/^\/+|\/+$/g,"");const parts=path.split("/").filter(Boolean),id=parts[1];
if(req.method==="GET"&&path==="health")return json(res,200,{ok:true,service:"nrroadcare-api",time:new Date().toISOString()});
if(req.method==="POST"&&path==="auth/login"){const{username,password}=req.body||{};if(!username||!password)return json(res,400,{error:"Username and password are required"});const r=await pool.query("select * from users where username=$1 and active=true",[username]);const u=r.rows[0];if(u&&u.password_hash===hash(password))return json(res,200,{token:token(u),user:{id:u.id,username:u.username,role:u.role,name:u.name,phone:u.phone}});const m=await pool.query("select id,name,phone,username,password_hash,active from technicians where username=$1 and active=true",[username]);const mech=m.rows[0];if(mech&&mech.password_hash===hash(password))return json(res,200,{token:token({id:mech.id,username:mech.username,role:"mechanic",name:mech.name,phone:mech.phone}),user:{id:mech.id,username:mech.username,role:"mechanic",name:mech.name,phone:mech.phone}});return json(res,401,{error:"Invalid username or password"})}
if(req.method==="GET"&&path==="auth/me"){const u=requireAuth(req,res);if(!u)return;return json(res,200,{user:u})}
if(req.method==="GET"&&path==="employees"){const u=requireAuth(req,res,["admin","division_manager","area_manager","tl"]);if(!u)return;const r=await pool.query("select id,username,role,name,phone,active,created_at from users where role <> 'admin' order by created_at desc");return json(res,200,r.rows)}
if(req.method==="POST"&&path==="employees"){const u=requireAuth(req,res,["admin","division_manager","area_manager","tl"]);if(!u)return;const{username,password,name,phone="",role="staff"}=req.body||{};if(!username||!password||!name)return json(res,400,{error:"name, username and password are required"});if(!ROLES.includes(role)||role==="customer"||role==="mechanic")return json(res,400,{error:"Invalid staff role"});const allowed=u.role==="admin"?["division_manager","area_manager","tl","staff"]:u.role==="division_manager"?["area_manager","tl","staff"]:u.role==="area_manager"?["tl","staff"]:["staff"];if(!allowed.includes(role))return json(res,403,{error:"You cannot create this role"});try{const r=await pool.query("insert into users(username,password_hash,role,name,phone) values($1,$2,$3,$4,$5) returning id,username,role,name,phone,active",[username,hash(password),role,name,phone]);return json(res,201,r.rows[0])}catch(e){if(e.code==="23505")return json(res,409,{error:"Username already exists"});throw e}}
if(req.method==="PATCH"&&parts[0]==="employees"&&id){const u=requireAuth(req,res,["admin","division_manager","area_manager","tl"]);if(!u)return;const r=await pool.query("update users set active=$1 where id=$2 and role <> 'admin' returning id,username,role,name,phone,active",[Boolean(req.body?.active),id]);return json(res,200,r.rows[0]||null)}
if(req.method==="GET"&&path==="dashboard"){if(!requireAuth(req,res))return;const[c,q,t,p]=await Promise.all([pool.query("select count(*)::int count from customers"),pool.query("select count(*)::int count from service_requests where status <> 'closed'"),pool.query("select count(*)::int count from technicians where active=true"),pool.query("select coalesce(sum(amount),0)::numeric total from payments")]);return json(res,200,{customers:c.rows[0].count,activeRequests:q.rows[0].count,techniciansOnline:t.rows[0].count,revenue:Number(p.rows[0].total)})}
if(req.method==="GET"&&path==="customers"){if(!requireAuth(req,res))return;const r=await pool.query("select * from customers order by created_at desc");return json(res,200,r.rows)}
if(req.method==="POST"&&path==="customers"){const u=requireAuth(req,res,["admin","division_manager","area_manager","tl","staff"]);if(!u)return;return json(res,409,{error:"Direct customer creation is disabled. Verify the customer mobile number by OTP first."})}
if(req.method==="POST"&&path==="customer-update-requests"){const u=requireAuth(req,res,["staff","tl","area_manager","division_manager"]);if(!u)return;const{customer_id,changes}=req.body||{};if(!customer_id||!changes)return json(res,400,{error:"customer_id and changes are required"});const r=await pool.query("insert into customer_update_requests(customer_id,requested_by,changes) values($1,$2,$3) returning *",[customer_id,u.id,JSON.stringify(changes)]);return json(res,201,r.rows[0])}
if(req.method==="GET"&&path==="customer-update-requests"){if(!requireAuth(req,res,["admin"]))return;const r=await pool.query("select r.*,c.name customer_name,u.name requested_by_name from customer_update_requests r join customers c on c.id=r.customer_id left join users u on u.id=r.requested_by where r.status='pending' order by r.created_at");return json(res,200,r.rows)}
if(req.method==="PATCH"&&parts[0]==="customer-update-requests"&&id){const u=requireAuth(req,res,["admin"]);if(!u)return;const{status}=req.body||{};if(!["approved","rejected"].includes(status))return json(res,400,{error:"Invalid status"});const r=await pool.query("select * from customer_update_requests where id=$1",[id]);const reqr=r.rows[0];if(!reqr)return json(res,404,{error:"Request not found"});if(status==="approved"){const c=reqr.changes||{};const fields=["name","phone","address","vehicle_no"].filter(k=>Object.prototype.hasOwnProperty.call(c,k));if(fields.length){const vals=fields.map(k=>c[k]);const sets=fields.map((k,i)=>`${k}=$${i+1}`).join(",");await pool.query(`update customers set ${sets} where id=$${fields.length+1}`,[...vals,reqr.customer_id]);}}const out=await pool.query("update customer_update_requests set status=$1,reviewed_by=$2,reviewed_at=now() where id=$3 returning *",[status,u.id,id]);return json(res,200,out.rows[0])}
if(req.method==="DELETE"&&parts[0]==="customers"&&id){if(!requireAuth(req,res,["admin"]))return;await pool.query("delete from customers where id=$1",[id]);return res.status(204).end()}
if(req.method==="GET"&&path==="requests"){if(!requireAuth(req,res))return;const r=await pool.query("select sr.*,c.name customer_name,c.phone customer_phone,c.vehicle_no,mo.status mechanic_order_status,mo.technician_id,mo.technician_name from service_requests sr left join customers c on c.id=sr.customer_id left join mechanic_orders mo on mo.request_id=sr.id order by sr.created_at desc");return json(res,200,r.rows)}
if(req.method==="POST"&&path==="requests"){if(!requireAuth(req,res,["admin","division_manager","area_manager","tl","staff","telecaller"]))return;const{customer_id,location="",description=""}=req.body||{};if(!customer_id)return json(res,400,{error:"Registered customer is required"});const c=await pool.query("select id from customers where id=$1",[customer_id]);if(!c.rowCount)return json(res,400,{error:"Registered customer is required"});const r=await pool.query("insert into service_requests(customer_id,location,description) values($1,$2,$3) returning *",[customer_id,location,description]);return json(res,201,r.rows[0])}
if(req.method==="PATCH"&&parts[0]==="requests"&&id){const u=requireAuth(req,res,["admin","division_manager","area_manager","tl","staff","telecaller"]);if(!u)return;const{status,assigned_technician}=req.body||{};const valid=["pending","assigned","on_the_way","completed","closed"];if(status&&!valid.includes(status))return json(res,400,{error:"Invalid request status"});if(assigned_technician!==undefined){if(!assigned_technician){await pool.query("delete from mechanic_orders where request_id=$1",[id]);const r=await pool.query("update service_requests set assigned_technician='',status=coalesce($1,status) where id=$2 returning *",[status||null,id]);return json(res,200,r.rows[0]||null)}const m=await pool.query("select id,name,phone,active from technicians where name=$1 and active=true limit 1",[assigned_technician]);if(!m.rowCount)return json(res,400,{error:"Selected mechanic is not active or was not found"});const tech=m.rows[0];const r=await pool.query("update service_requests set status='assigned',assigned_technician=$1 where id=$2 returning *",[tech.name,id]);if(!r.rowCount)return json(res,404,{error:"Request not found"});await pool.query(`insert into mechanic_orders(request_id,technician_id,technician_name,status,assigned_by) values($1,$2,$3,'sent',$4) on conflict(request_id) do update set technician_id=excluded.technician_id,technician_name=excluded.technician_name,status='sent',assigned_by=excluded.assigned_by,accepted_at=null,started_at=null,completed_at=null`,[id,tech.id,tech.name,u.id]);return json(res,200,{...r.rows[0],mechanic_order_sent:true,technician_id:tech.id,technician_name:tech.name})}const r=await pool.query("update service_requests set status=coalesce($1,status) where id=$2 returning *",[status,id]);if(status==="completed")await pool.query("update mechanic_orders set status='completed',completed_at=coalesce(completed_at,now()) where request_id=$1",[id]);return json(res,200,r.rows[0]||null)}
if(req.method==="GET"&&path==="technicians"){if(!requireAuth(req,res))return;const r=await pool.query("select * from technicians order by name");return json(res,200,r.rows)}
if(req.method==="POST"&&path==="technicians"){if(!requireAuth(req,res,["admin","division_manager","area_manager"]))return;const{name,phone,specialization=""}=req.body||{};if(!name||!phone)return json(res,400,{error:"name and phone are required"});const r=await pool.query("insert into technicians(name,phone,specialization) values($1,$2,$3) returning *",[name,phone,specialization]);return json(res,201,r.rows[0])}
if(req.method==="POST"&&path==="payments"){if(!requireAuth(req,res,["admin","division_manager","area_manager","tl","staff"]))return;const{customer_id,amount=4500,method="UPI",transaction_ref=""}=req.body||{};const payment=await pool.query("insert into payments(customer_id,amount,method,transaction_ref) values($1,$2,$3,$4) returning *",[customer_id||null,amount,method,transaction_ref]);const receiptNo="NR-"+new Date().getFullYear()+"-"+crypto.randomBytes(4).toString("hex").toUpperCase();const receipt=await pool.query("insert into receipts(customer_id,payment_id,receipt_no) values($1,$2,$3) returning *",[customer_id||null,payment.rows[0].id,receiptNo]);return json(res,201,{payment:payment.rows[0],receipt:receipt.rows[0]})}
if(req.method==="POST"&&path==="memberships/renew"){if(!requireAuth(req,res,["admin","division_manager","area_manager","tl","staff"]))return;const{customer_id,renewal_date}=req.body||{};if(!customer_id||!renewal_date)return json(res,400,{error:"customer_id and renewal_date are required"});const r=await pool.query("insert into memberships(customer_id,amount,renewal_date) values($1,4500,$2) returning *",[customer_id,renewal_date]);return json(res,201,r.rows[0])}
return json(res,404,{error:"Not found"})}catch(e){console.error(e);return json(res,500,{error:e?.message||"Internal server error"})}}
