import pg from "pg";
import crypto from "crypto";
const { Pool } = pg;
const pool = globalThis.__nroraCustomersPool || new Pool({ connectionString: process.env.DATABASE_URL, max: 3, idleTimeoutMillis: 10000 });
globalThis.__nroraCustomersPool = pool;
const SECRET = process.env.SESSION_SECRET || "change-this-session-secret-in-vercel";
const readToken = token => { try { const [p,s]=String(token||"").split("."); const u=JSON.parse(Buffer.from(p,"base64url").toString()); const e=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex"); if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))||u.exp<Date.now()) return null; return u; } catch { return null; } };
const auth = (req,res,roles=[]) => { const u=readToken((req.headers.authorization||"").replace(/^Bearer\s+/i,"")); if(!u || (roles.length && !roles.includes(u.role))){res.status(401).json({error:"Unauthorized"});return null} return u; };
async function schema(){
  await pool.query(`create table if not exists customers(id bigserial primary key,name varchar(120) not null,phone varchar(20) not null,address text default '',vehicle_no varchar(30) not null,created_at timestamptz default now());`);
  const cols=[["house_number","text default ''"],["landmark","text default ''"],["state","varchar(80) default 'Telangana'"],["district","varchar(120) default ''"],["mandal","varchar(120) default ''"],["village","varchar(120) default ''"],["pincode","varchar(10) default ''"],["vehicle_type","varchar(80) default ''"],["make_brand","varchar(100) default ''"],["model","varchar(100) default ''"],["variant","varchar(100) default ''"],["manufacturing_year","varchar(10) default ''"],["color","varchar(60) default ''"],["rc_number","varchar(80) default ''"],["vehicle_photos","jsonb default '[]'::jsonb"],["account_status","varchar(30) default 'inactive'"],["mobile_verified","boolean default false"],["membership_start","date"],["membership_end","date"],["referral_code","varchar(40) default ''"],["referred_by","varchar(40) default ''"]];
  for(const [name,type] of cols) await pool.query(`alter table customers add column if not exists ${name} ${type}`);
}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(req.method==="OPTIONS")return res.status(204).end();try{await schema();const u=auth(req,res,["ceo","admin","division_manager","area_manager","tl","staff","telecaller"]);if(!u)return;
  if(req.method==="GET"){const r=await pool.query("select * from customers order by created_at desc");return res.status(200).json(r.rows)}
  if(req.method==="POST"){const b=req.body||{};const name=String(b.name||"").trim(),phone=String(b.phone||"").replace(/\D/g,""),vehicle_no=String(b.vehicle_no||"").trim().toUpperCase();if(!name||phone.length!==10||!vehicle_no)return res.status(400).json({error:"Name, valid 10-digit mobile number and vehicle number are required"});const exists=await pool.query("select id from customers where phone=$1",[phone]);if(exists.rowCount)return res.status(409).json({error:"A customer account already exists for this mobile number"});const r=await pool.query(`insert into customers(name,phone,address,vehicle_no,house_number,landmark,state,district,mandal,village,pincode,vehicle_type,make_brand,model,variant,manufacturing_year,color,rc_number,vehicle_photos,account_status,referral_code,referred_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,'inactive',$20,$21) returning *`,[name,phone,String(b.address||""),vehicle_no,String(b.house_number||""),String(b.landmark||""),String(b.state||"Telangana"),String(b.district||""),String(b.mandal||""),String(b.village||""),String(b.pincode||""),String(b.vehicle_type||""),String(b.make_brand||""),String(b.model||""),String(b.variant||""),String(b.manufacturing_year||""),String(b.color||""),String(b.rc_number||""),JSON.stringify(Array.isArray(b.vehicle_photos)?b.vehicle_photos.slice(0,2):[]),String(b.referral_code||""),String(b.referred_by||"")]);return res.status(201).json(r.rows[0])}
  return res.status(405).json({error:"Method not allowed"});
}catch(e){console.error("customers api",e);return res.status(500).json({error:e.message||"Customer service unavailable"})}}
