import pg from "pg";
import crypto from "crypto";
const { Pool } = pg;
const pool = globalThis.__nroraCustomerDetailsPool || new Pool({connectionString:process.env.DATABASE_URL,max:5,idleTimeoutMillis:10000});
globalThis.__nroraCustomerDetailsPool=pool;
const SECRET=process.env.SESSION_SECRET||"change-this-session-secret-in-vercel";
const roles=["ceo","admin","division_manager","area_manager","tl","staff","telecaller","employee"];
const json=(res,s,b)=>res.status(s).json(b);
function user(req){try{const raw=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");const [p,s]=raw.split(".");if(!p||!s)return null;const u=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));const e=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");if(s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))||Number(u.exp)<Date.now())return null;return u}catch{return null}}
async function schema(){await pool.query(`create table if not exists customer_details(customer_id bigint primary key references customers(id) on delete cascade,house_number varchar(120) default '',landmark varchar(200) default '',state varchar(80) default 'Telangana',district varchar(120) default '',mandal varchar(120) default '',village varchar(120) default '',pincode varchar(6) default '',registration_number varchar(40) default '',vehicle_type varchar(60) default '',make_brand varchar(100) default '',model varchar(100) default '',variant varchar(100) default '',manufacturing_year varchar(4) default '',color varchar(60) default '',rc_number varchar(80) default '',back_photo text default '',rc_photo text default '',other_document text default '',updated_at timestamptz default now())`)}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Methods","GET,POST,OPTIONS");if(req.method==="OPTIONS")return res.status(204).end();try{const u=user(req);if(!u||!roles.includes(u.role))return json(res,401,{error:"Unauthorized"});await schema();if(req.method==="POST"){const b=req.body||{},id=Number(b.customer_id);if(!id)return json(res,400,{error:"customer_id is required"});const q=await pool.query(`insert into customer_details(customer_id,house_number,landmark,state,district,mandal,village,pincode,registration_number,vehicle_type,make_brand,model,variant,manufacturing_year,color,rc_number,back_photo,rc_photo,other_document,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,now()) on conflict(customer_id) do update set house_number=excluded.house_number,landmark=excluded.landmark,state=excluded.state,district=excluded.district,mandal=excluded.mandal,village=excluded.village,pincode=excluded.pincode,registration_number=excluded.registration_number,vehicle_type=excluded.vehicle_type,make_brand=excluded.make_brand,model=excluded.model,variant=excluded.variant,manufacturing_year=excluded.manufacturing_year,color=excluded.color,rc_number=excluded.rc_number,back_photo=excluded.back_photo,rc_photo=excluded.rc_photo,other_document=excluded.other_document,updated_at=now() returning *`,[id,String(b.house_number||""),String(b.landmark||""),"Telangana",String(b.district||""),String(b.mandal||""),String(b.village||""),String(b.pincode||""),String(b.registration_number||"").toUpperCase(),String(b.vehicle_type||""),String(b.make_brand||""),String(b.model||""),String(b.variant||""),String(b.manufacturing_year||""),String(b.color||""),String(b.rc_number||""),String(b.back_photo||""),String(b.rc_photo||""),String(b.other_document||"")]);return json(res,200,{ok:true,details:q.rows[0]})}if(req.method==="GET"){const id=Number(req.query?.customer_id);if(!id)return json(res,400,{error:"customer_id is required"});const q=await pool.query("select * from customer_details where customer_id=$1",[id]);return json(res,200,q.rows[0]||null)}return json(res,405,{error:"Method not allowed"})}catch(e){console.error("Customer details API",e);return json(res,500,{error:e.message||"Unable to save customer details"})}}
