import pg from "pg";
import crypto from "crypto";
const { Pool } = pg;
const pool = globalThis.__nroraOtpPool || new Pool({ connectionString: process.env.DATABASE_URL, max: 5, idleTimeoutMillis: 10000 });
globalThis.__nroraOtpPool = pool;
const SECRET = process.env.SESSION_SECRET || "change-this-session-secret-in-vercel";
const json=(res,status,body)=>res.status(status).json(body);
const readUser=req=>{try{const value=String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");const [payload,signature]=value.split(".");if(!payload||!signature)return null;const user=JSON.parse(Buffer.from(payload,"base64url").toString("utf8"));const expected=crypto.createHmac("sha256",SECRET).update(`${user.id}:${user.username}:${user.role}`).digest("hex");if(signature.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(signature),Buffer.from(expected))||!user.exp||Number(user.exp)<Date.now())return null;return user}catch{return null}};
const staffRoles=["admin","division_manager","area_manager","tl","staff"];
const normalizePhone=p=>{const d=String(p||"").replace(/\D/g,"");return d.length===10?`91${d}`:d.startsWith("91")?d:d};
async function schema(){await pool.query(`alter table customers add column if not exists mobile_verified boolean not null default false; alter table customers add column if not exists account_status varchar(20) not null default 'active'; alter table customers add column if not exists vehicle_photos jsonb not null default '[]'::jsonb; create table if not exists customer_otp_verifications(id uuid primary key,phone varchar(20) not null,payload jsonb not null,expires_at timestamptz not null,attempts integer not null default 0,created_at timestamptz default now());`)}
async function sendOtp(mobile){const auth=process.env.MSG91_AUTH_KEY;const template=process.env.MSG91_OTP_TEMPLATE_ID;if(!auth||!template)throw new Error("OTP service is not configured. Add MSG91_AUTH_KEY and MSG91_OTP_TEMPLATE_ID in Vercel environment variables.");const url=`https://control.msg91.com/api/v5/otp?template_id=${encodeURIComponent(template)}&mobile=${encodeURIComponent(mobile)}&authkey=${encodeURIComponent(auth)}`;const r=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"}});let body={};try{body=await r.json()}catch{};if(!r.ok||String(body.type||"").toLowerCase()==="error")throw new Error(body.message||"Unable to send OTP");return body}
async function verifyOtp(mobile,otp){const auth=process.env.MSG91_AUTH_KEY;if(!auth)throw new Error("OTP service is not configured.");const url=`https://control.msg91.com/api/v5/otp/verify?otp=${encodeURIComponent(otp)}&mobile=${encodeURIComponent(mobile)}`;const r=await fetch(url,{headers:{authkey:auth}});let body={};try{body=await r.json()}catch{};const ok=r.ok&&String(body.type||body.message||"").toLowerCase().includes("success");return {ok,body}}
export default async function handler(req,res){try{if(req.method!=="POST")return json(res,405,{error:"POST required"});const user=readUser(req);if(!user||!staffRoles.includes(user.role))return json(res,401,{error:"Unauthorized"});await schema();const {action="send",verificationId,name,phone,address="",vehicle_no,vehicle_photos=[],otp}=req.body||{};const mobile=normalizePhone(phone);if(mobile.length!==12)return json(res,400,{error:"Enter a valid 10-digit Indian mobile number"});
if(action==="send"){if(!name||!vehicle_no)return json(res,400,{error:"Name and vehicle number are required"});const id=crypto.randomUUID();await pool.query("delete from customer_otp_verifications where phone=$1",[mobile]);await sendOtp(mobile);await pool.query("insert into customer_otp_verifications(id,phone,payload,expires_at) values($1,$2,$3,now()+interval '10 minutes')",[id,mobile,JSON.stringify({name,phone:String(phone),address,vehicle_no,vehicle_photos:Array.isArray(vehicle_photos)?vehicle_photos.slice(0,5):[]})]);return json(res,200,{ok:true,verificationId:id,message:"OTP sent to customer mobile number"})}
if(action==="verify"){if(!verificationId||!otp)return json(res,400,{error:"Verification ID and OTP are required"});const q=await pool.query("select * from customer_otp_verifications where id=$1 and expires_at>now()",[verificationId]);const pending=q.rows[0];if(!pending)return json(res,400,{error:"OTP expired or verification request not found. Send a new OTP."});if(pending.attempts>=5)return json(res,429,{error:"Too many OTP attempts. Send a new OTP."});await pool.query("update customer_otp_verifications set attempts=attempts+1 where id=$1",[verificationId]);const check=await verifyOtp(pending.phone,String(otp).trim());if(!check.ok)return json(res,400,{error:"Invalid OTP. Please try again."});const p=pending.payload||{};const exists=await pool.query("select id from customers where phone=$1 and account_status='active'",[p.phone]);if(exists.rowCount)return json(res,409,{error:"A customer account already exists for this mobile number"});const c=await pool.query("insert into customers(name,phone,address,vehicle_no,mobile_verified,account_status,vehicle_photos) values($1,$2,$3,$4,true,'active',$5) returning *",[p.name,p.phone,p.address||"",p.vehicle_no,JSON.stringify(p.vehicle_photos||[])]);await pool.query("delete from customer_otp_verifications where id=$1",[verificationId]);return json(res,201,{ok:true,customer:c.rows[0],message:"Mobile verified. Customer account is now active."})}
return json(res,400,{error:"Invalid action"});}catch(e){console.error("NRORA customer OTP error",e);return json(res,500,{error:e?.message||"OTP verification failed"})}}
