import pg from "pg";
import crypto from "crypto";
const { Pool }=pg;
const pool=globalThis.__nroraCustomerDetailsPool||new Pool({connectionString:process.env.DATABASE_URL,max:2,idleTimeoutMillis:10000});
globalThis.__nroraCustomerDetailsPool=pool;
const SECRET=process.env.SESSION_SECRET||"change-this-session-secret-in-vercel";
const readToken=t=>{try{const[p,s]=String(t||"").split(".");const u=JSON.parse(Buffer.from(p,"base64url").toString());const e=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");if(!s||s.length!==e.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(e))||u.exp<Date.now())return null;return u}catch{return null}};
const allowed=["ceo","admin","division_manager","area_manager","tl","staff","telecaller"];
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");if(req.method==="OPTIONS")return res.status(204).end();const u=readToken((req.headers.authorization||"").replace(/^Bearer\s+/i,""));if(!u||!allowed.includes(u.role))return res.status(401).json({error:"Unauthorized"});try{
await pool.query(`alter table customers add column if not exists house_number text default '';alter table customers add column if not exists landmark text default '';alter table customers add column if not exists state varchar(80) default 'Telangana';alter table customers add column if not exists district varchar(120) default '';alter table customers add column if not exists mandal varchar(120) default '';alter table customers add column if not exists village varchar(120) default '';alter table customers add column if not exists pincode varchar(10) default '';alter table customers add column if not exists vehicle_type varchar(80) default '';alter table customers add column if not exists make_brand varchar(100) default '';alter table customers add column if not exists model varchar(100) default '';alter table customers add column if not exists variant varchar(100) default '';alter table customers add column if not exists manufacturing_year varchar(10) default '';alter table customers add column if not exists color varchar(60) default '';alter table customers add column if not exists rc_number varchar(80) default '';alter table customers add column if not exists vehicle_photos jsonb default '[]'::jsonb;`);
if(req.method!=="PATCH")return res.status(405).json({error:"Method not allowed"});
const b=req.body||{},id=Number(b.customer_id);if(!id)return res.status(400).json({error:"Customer ID is required"});
const r=await pool.query(`update customers set house_number=$1,landmark=$2,state=$3,district=$4,mandal=$5,village=$6,pincode=$7,vehicle_type=$8,make_brand=$9,model=$10,variant=$11,manufacturing_year=$12,color=$13,rc_number=$14,vehicle_photos=$15 where id=$16 returning *`,[String(b.house_number||""),String(b.landmark||""),String(b.state||"Telangana"),String(b.district||""),String(b.mandal||""),String(b.village||""),String(b.pincode||""),String(b.vehicle_type||""),String(b.make_brand||""),String(b.model||""),String(b.variant||""),String(b.manufacturing_year||""),String(b.color||""),String(b.rc_number||""),JSON.stringify(Array.isArray(b.vehicle_photos)?b.vehicle_photos.slice(0,2):[]),id]);
if(!r.rowCount)return res.status(404).json({error:"Customer not found"});return res.status(200).json({ok:true,customer:r.rows[0]});
}catch(e){console.error("customer-details",e);return res.status(500).json({error:e.message||"Unable to save customer details"})}}
