import pg from "pg";
import crypto from "crypto";
const {Pool}=pg;
const pool=globalThis.__nroraMechanicOrdersPool||new Pool({connectionString:process.env.DATABASE_URL,max:5,idleTimeoutMillis:10000});
globalThis.__nroraMechanicOrdersPool=pool;
const SECRET=process.env.SESSION_SECRET||"change-this-session-secret-in-vercel";
const json=(res,status,body)=>res.status(status).json(body);
function token(req){try{const [p,s]=String((req.headers.authorization||"").replace(/^Bearer\s+/i,"")).split(".");const u=JSON.parse(Buffer.from(p,"base64url").toString());const sig=crypto.createHmac("sha256",SECRET).update(`${u.id}:${u.username}:${u.role}`).digest("hex");if(!s||s.length!==sig.length||!crypto.timingSafeEqual(Buffer.from(s),Buffer.from(sig))||u.exp<Date.now())return null;return u}catch{return null}}
async function schema(){await pool.query(`create table if not exists mechanic_orders(id bigserial primary key,request_id bigint unique references service_requests(id) on delete cascade,technician_id bigint references technicians(id) on delete set null,technician_name varchar(120) default '',status varchar(30) default 'sent',assigned_by bigint,created_at timestamptz default now(),accepted_at timestamptz,started_at timestamptz,completed_at timestamptz)`)}
export default async function handler(req,res){res.setHeader("Access-Control-Allow-Origin","*");res.setHeader("Access-Control-Allow-Headers","Content-Type, Authorization");res.setHeader("Access-Control-Allow-Methods","GET,PATCH,OPTIONS");if(req.method==="OPTIONS")return res.status(204).end();const u=token(req);if(!u)return json(res,401,{error:"Unauthorized"});try{await schema();if(u.role!=="mechanic")return json(res,403,{error:"Mechanic access required"});if(req.method==="GET"){const r=await pool.query(`select mo.*,sr.status request_status,sr.location,sr.description,c.name customer_name,c.phone customer_phone,c.vehicle_no from mechanic_orders mo join service_requests sr on sr.id=mo.request_id left join customers c on c.id=sr.customer_id where mo.technician_id=$1 order by mo.created_at desc`,[u.id]);return json(res,200,r.rows)}if(req.method==="PATCH"){const id=req.query?.id;if(!id)return json(res,400,{error:"Order id is required"});const {status}=req.body||{};const allowed=["accepted","on_the_way","reached","service_started","completed"];if(!allowed.includes(status))return json(res,400,{error:"Invalid mechanic order status"});const times={accepted:"accepted_at",on_the_way:"started_at",service_started:"started_at",completed:"completed_at"};const col=times[status];const r=await pool.query(`update mechanic_orders set status=$1,${col?`${col}=coalesce(${col},now()),`:""} accepted_at=case when $1='accepted' then coalesce(accepted_at,now()) else accepted_at end where id=$2 and technician_id=$3 returning *`,[status,id,u.id]);if(!r.rowCount)return json(res,404,{error:"Order not found"});const requestStatus=status==="accepted"?"assigned":status==="on_the_way"?"on_the_way":status==="completed"?"completed":"assigned";await pool.query("update service_requests set status=$1 where id=$2",[requestStatus,r.rows[0].request_id]);return json(res,200,r.rows[0])}return json(res,405,{error:"Method not allowed"})}catch(e){console.error(e);return json(res,500,{error:e?.message||"Internal server error"})}}
