import React,{useEffect,useState} from "react";
import {Routes,Route,NavLink,Navigate} from "react-router-dom";
import {Home,Users,MapPin,Settings,Phone,Globe,Map,UserPlus,Menu,X,Plus,Trash2,RefreshCw,UserCog,LogOut} from "lucide-react";
const API=import.meta.env.VITE_API_URL || "/api"; const phone="9160264439",domain="nrroadcare.in";
const getToken=()=>localStorage.getItem("nrora_token");
const api=async(path,options={})=>{const headers={...(options.body?{"Content-Type":"application/json"}:{}),...(getToken()?{Authorization:`Bearer ${getToken()}`}:{})};const r=await fetch(`${API}${path}`,{...options,headers});if(!r.ok){let e={};try{e=await r.json()}catch{};throw new Error(e.error||`Request failed (${r.status})`)}return r.status===204?null:r.json()};
function Layout({user,onLogout}){const[open,setOpen]=useState(false);const links=[["/",Home,"Dashboard"],["/requests",MapPin,"Requests"],["/customers",UserPlus,"Customers"],["/technicians",Users,"Technicians"],["/payments",RefreshCw,"Payments"],["/employees",UserCog,"Employees"],["/settings",Settings,"Settings"],["/contact",Map,"Contact"]];return <div className="shell"><button className="mobile" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><aside className={open?"side open":"side"}><div className="brand"><div className="logo">NR</div><div><b>NRORA</b><small>Road Assistance</small></div></div><div className="userbox"><b>{user.name}</b><small>{user.role}</small><button onClick={onLogout}><LogOut size={14}/> Logout</button></div><nav>{links.filter(x=>x[0]!=="/employees"||user.role==="admin").map(([to,I,label])=><NavLink key={to} to={to} end={to==="/"} onClick={()=>setOpen(false)} className={({isActive})=>isActive?"nav active":"nav"}><I size={18}/>{label}</NavLink>)}</nav><div className="footer"><a href={`tel:${phone}`}><Phone size={15}/>{phone}</a><a href={`https://${domain}`} target="_blank" rel="noreferrer"><Globe size={15}/>{domain}</a><span><Map size={15}/>Mugpal Village, Mugpal Mandal,<br/>Nizamabad District, Telangana 503230</span></div></aside><main><Routes><Route path="/" element={<Dashboard/>}/><Route path="/customers" element={<Customers/>}/><Route path="/requests" element={<Requests/>}/><Route path="/technicians" element={<Technicians/>}/><Route path="/payments" element={<Payments/>}/><Route path="/employees" element={user.role==="admin"?<Employees/>:<Navigate to="/" replace/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="/contact" element={<Contact/>}/></Routes></main></div>}
function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{api("/dashboard").then(setD).catch(()=>{})},[]);return <Page title="Dashboard" sub="NRORA operations"><div className="stats"><Stat t="Customers" v={d?.customers??"—"}/><Stat t="Active Requests" v={d?.activeRequests??"—"}/><Stat t="Technicians" v={d?.techniciansOnline??"—"}/><Stat t="Revenue" v={d?`₹${d.revenue}`:"—"}/></div><div className="card"><h2>Yearly Membership</h2><p className="muted">₹4,500 per year</p><p className="muted">Payment, receipt and renewal APIs are ready for integration.</p></div></Page>}
const Stat=({t,v})=><div className="stat"><small>{t}</small><strong>{v}</strong></div>;
function Customers(){const[rows,setRows]=useState([]),[f,setF]=useState({name:"",phone:"",address:"",vehicle_no:""}),[error,setError]=useState("");const load=()=>api("/customers").then(setRows).catch(e=>setError(e.message));useEffect(load,[]);const add=async e=>{e.preventDefault();setError("");try{await api("/customers",{method:"POST",body:JSON.stringify(f)});setF({name:"",phone:"",address:"",vehicle_no:""});load()}catch(e){setError(e.message)}};const del=async id=>{try{await api(`/customers/${id}`,{method:"DELETE"});load()}catch(e){setError(e.message)}};return <Page title="Customers" sub="Customer records"><div className="cols"><form className="card form" onSubmit={add}><h2><Plus size={18}/> Add Customer</h2>{Object.keys(f).map(k=><label key={k}>{k.replace("_"," ").toUpperCase()}<input required={k!=="address"} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/></label>)}{error&&<p className="error">{error}</p>}<button className="primary" type="submit">Add Customer</button></form><div className="card"><h2>Customer List</h2>{rows.length===0?<p className="muted">No customers yet.</p>:rows.map(c=><div className="row" key={c.id}><div><b>{c.name}</b><small>{c.phone} · {c.vehicle_no}</small><small>{c.address}</small></div><button className="danger" type="button" onClick={()=>del(c.id)}><Trash2 size={17}/></button></div>)}</div></div></Page>}
function Employees(){const[rows,setRows]=useState([]),[f,setF]=useState({name:"",username:"",password:"",phone:""}),[error,setError]=useState("");const load=()=>api("/employees").then(setRows).catch(e=>setError(e.message));useEffect(load,[]);const add=async e=>{e.preventDefault();setError("");try{await api("/employees",{method:"POST",body:JSON.stringify(f)});setF({name:"",username:"",password:"",phone:""});load()}catch(e){setError(e.message)}};const toggle=async u=>{try{await api(`/employees/${u.id}`,{method:"PATCH",body:JSON.stringify({active:!u.active})});load()}catch(e){setError(e.message)}};return <Page title="Employees" sub="Admin can create and manage employee accounts"><div className="cols"><form className="card form" onSubmit={add}><h2><UserPlus size={18}/> Create Employee</h2><label>NAME<input required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></label><label>USERNAME<input required value={f.username} onChange={e=>setF({...f,username:e.target.value})}/></label><label>PASSWORD<input required type="password" minLength="6" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/></label><label>PHONE<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label>{error&&<p className="error">{error}</p>}<button className="primary">Create Employee</button></form><div className="card"><h2>Employee List</h2>{rows.length===0?<p className="muted">No employees yet.</p>:rows.map(u=><div className="row" key={u.id}><div><b>{u.name}</b><small>@{u.username} · {u.phone||"No phone"}</small><small>{u.active?"Active":"Disabled"}</small></div><button className={u.active?"danger":"primary"} type="button" onClick={()=>toggle(u)}>{u.active?"Disable":"Enable"}</button></div>)}</div></div></Page>}
function Requests(){return <Page title="Service Requests" sub="Live roadside assistance requests"><div className="card empty"><MapPin/><h2>Requests API ready</h2><p className="muted">Connect the mobile request form to POST /api/requests.</p></div></Page>}
function Technicians(){return <Page title="Technicians" sub="Mechanic and field technician management"><div className="card empty"><Users/><h2>Technician API ready</h2><p className="muted">Add technicians through POST /api/technicians.</p></div></Page>}
function Payments(){return <Page title="Payments & Receipts" sub="Membership payment and instant receipt workflow"><div className="card"><h2>Membership</h2><p className="muted">₹4,500 · UPI / QR supported at API layer.</p><p className="muted">Payment creates a receipt number automatically.</p></div></Page>}
function SettingsPage(){return <Page title="Settings" sub="System configuration"><div className="card"><h2>NRORA</h2><p className="muted">Domain: {domain}</p><p className="muted">Membership: ₹4,500 / year</p><p className="muted">Phone: {phone}</p></div></Page>}
function Contact(){return <Page title="Contact Us" sub="Mugpal Village, Mugpal Mandal, Nizamabad District, Telangana 503230"><div className="card"><a className="primary" href={`tel:${phone}`}><Phone/> Call {phone}</a></div></Page>}
const Page=({title,sub,children})=><section><div className="head"><div><span>NRORA</span><h1>{title}</h1><p>{sub}</p></div></div>{children}</section>;
function Login({onLogin}){const[username,setUsername]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState("");const submit=async e=>{e.preventDefault();setError("");try{const r=await api("/auth/login",{method:"POST",body:JSON.stringify({username,password})});localStorage.setItem("nrora_token",r.token);onLogin(r.user)}catch(e){setError(e.message)}};return <div className="loginwrap"><form className="card form login" onSubmit={submit}><div className="brand"><div className="logo">NR</div><div><b>NRORA</b><small>Admin / Employee Login</small></div></div><h1>Sign in</h1><label>USERNAME<input required autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)}/></label><label>PASSWORD<input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button className="primary">Login</button></form></div>}
export default function App(){const[user,setUser]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{if(!getToken()){setLoading(false);return}api("/auth/me").then(r=>setUser(r.user)).catch(()=>localStorage.removeItem("nrora_token")).finally(()=>setLoading(false))},[]);if(loading)return <div className="loginwrap"><p>Loading NRORA...</p></div>;if(!user)return <Login onLogin={setUser}/>;return <Layout user={user} onLogout={()=>{localStorage.removeItem("nrora_token");setUser(null)}}/>}
