import React,{useEffect,useMemo,useState} from "react";

const API="/api";
const token=()=>localStorage.getItem("nrora_ceo_token");
const api=async(path,options={})=>{const r=await fetch(API+path,{...options,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token()||""}`}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d};
const roles=["admin","division_manager","area_manager","tl","staff","telecaller","mechanic"];
const labels={admin:"Admin",division_manager:"Division Manager",area_manager:"Area Manager",tl:"Team Leader (TL)",staff:"Staff",telecaller:"Telecaller",mechanic:"Mechanic"};
const permissionGroups=[
 ["Dashboard",[["dashboard_view","View Dashboard"]]],
 ["Requests",[["requests_view","View Requests"],["requests_create","Create Requests"],["requests_manage","Manage Requests"]]],
 ["Customers",[["customers_view","View Customers"],["customers_create","Create Customers"],["customers_delete","Delete Customers"]]],
 ["Payments",[["payments_view","View Payments"],["payments_manage","Manage Payments"]]],
 ["Technicians",[["technicians_view","View Technicians"],["technicians_manage","Manage Technicians"]]],
 ["Employees",[["employees_view","View Employees"],["employees_create","Create Employees"],["employees_manage","Manage Employees"]]],
 ["Work Orders",[["workorders_view","View Work Orders"],["workorders_manage","Manage Work Orders"]]],
 ["Settings",[["settings_view","View Settings"]]]
];
const defaultSettings={company_name:"",phone:"",website:"",service_network:"",address:"",upi_id:"",membership_amount:"",renewal_period:"",customer_verification:"",work_order:""};
function Card({children,style}){return <section style={{background:"#fff",border:"1px solid #dce5f2",borderRadius:16,padding:18,boxShadow:"0 8px 26px rgba(16,33,62,.07)",...style}}>{children}</section>}
function Btn({children,onClick,type="button",danger=false,disabled=false}){return <button type={type} disabled={disabled} onClick={onClick} style={{border:0,borderRadius:9,padding:"10px 14px",fontWeight:800,cursor:disabled?"not-allowed":"pointer",background:danger?"#d83a3a":"#2367df",color:"#fff",opacity:disabled?.6:1}}>{children}</button>}
function Input({label,...p}){return <label style={{display:"block",fontSize:11,fontWeight:800,marginBottom:10}}>{label}<input {...p} style={{width:"100%",boxSizing:"border-box",padding:10,border:"1px solid #cbd7e7",borderRadius:9,marginTop:5}}/></label>}
function CeoApp(){const[page,setPage]=useState(location.hash.replace(/^#/,'')||"dashboard");const[msg,setMsg]=useState("");const go=p=>{location.hash=p;setPage(p);setMsg("")};useEffect(()=>{const f=()=>setPage(location.hash.replace(/^#/,'')||"dashboard");addEventListener("hashchange",f);return()=>removeEventListener("hashchange",f)},[]);const logout=()=>{localStorage.removeItem("nrora_ceo_token");localStorage.removeItem("nrora_token");location.href="/ceo.html"};return <div style={{minHeight:"100vh",background:"#eef3fa",color:"#10213e",fontFamily:"Inter,Arial,sans-serif"}}><header style={{background:"#061a39",color:"#fff",padding:"16px 24px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:21,fontWeight:900}}>NRORA CEO CONTROL</div><small>Complete Admin & System Authority</small></div><Btn danger onClick={logout}>Logout</Btn></header><main style={{maxWidth:1180,margin:"20px auto",padding:"0 16px"}}><div style={{display:"grid",gridTemplateColumns:"210px 1fr",gap:16}}><aside><Card><b>CEO OPERATIONS</b>{[["dashboard","🏠 Dashboard"],["requests","📍 Requests"],["customers","👥 Customers"],["technicians","🔧 Technicians"],["employees","👨‍💼 Employees"],["payments","💳 Payments"],["settings","⚙️ Settings"],["permissions","🛡️ Permissions"],["contact","📞 Contact"]].map(([p,t])=><button key={p} onClick={()=>go(p)} style={{display:"block",width:"100%",textAlign:"left",border:0,borderRadius:8,padding:"11px 10px",marginTop:5,cursor:"pointer",background:page===p?"#2367df":"transparent",color:page===p?"#fff":"#10213e",fontWeight:700}}>{t}</button>)}</Card></aside><section>{msg&&<div style={{background:"#e9f8ef",color:"#087443",padding:10,borderRadius:9,marginBottom:12}}>{msg}</div>}{page==="dashboard"&&<Dashboard/>}{page==="employees"&&<Employees setMsg={setMsg}/>} {page==="settings"&&<Settings setMsg={setMsg}/>} {page==="permissions"&&<Permissions setMsg={setMsg}/>} {page==="requests"&&<Requests/>}{page==="customers"&&<Customers/>}{page==="technicians"&&<Technicians/>}{page==="payments"&&<Payments/>}{page==="contact"&&<Contact/>}</section></div></main></div>}
function Dashboard(){const[d,setD]=useState(null);useEffect(()=>{api("/dashboard").then(setD).catch(()=>{})},[]);return <><h1>CEO Dashboard</h1><p style={{color:"#6a7b93"}}>CEO has complete system authority.</p><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[["Customers",d?.customers], ["Active Requests",d?.activeRequests],["Technicians",d?.techniciansOnline],["Revenue",d?`₹${d.revenue}`:"—"]].map(([a,b])=><Card key={a}><small>{a}</small><h2 style={{margin:"8px 0 0"}}>{b??"—"}</h2></Card>)}</div><Card style={{marginTop:16}}><h2>CEO Authority</h2><p>CEO → Admin → Division Manager → Area Manager → TL → Staff / Telecaller → Mechanic</p><p style={{color:"#6a7b93"}}>Admin accounts, employee roles, permissions and company settings are controlled here.</p></Card></>}
function Employees({setMsg}){const[f,setF]=useState({name:"",username:"",password:"",phone:"",role:"admin"});const[rows,setRows]=useState([]);const[admins,setAdmins]=useState([]);const load=async()=>{try{setRows(await api("/employees"));setAdmins(await api("/ceo/admins"))}catch(e){setMsg(e.message)}};useEffect(()=>{load()},[]);const add=async e=>{e.preventDefault();try{if(f.role==="admin")await api("/ceo/admins",{method:"POST",body:JSON.stringify(f)});else await api("/employees",{method:"POST",body:JSON.stringify(f)});setF({name:"",username:"",password:"",phone:"",role:"admin"});setMsg(`${labels[f.role]} created successfully.`);load()}catch(e){setMsg(e.message)}};const toggle=async(a,active)=>{try{await api(`/ceo/admins/${a.id}`,{method:"PATCH",body:JSON.stringify({active})});load()}catch(e){setMsg(e.message)}};return <><h1>Employees & Roles</h1><p style={{color:"#6a7b93"}}>CEO can create Admin and every employee role.</p><Card><h2>➕ Create Team Member</h2><form onSubmit={add} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><Input label="NAME" required value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><Input label="USERNAME" required value={f.username} onChange={e=>setF({...f,username:e.target.value})}/><Input label="PASSWORD" required minLength={6} type="password" value={f.password} onChange={e=>setF({...f,password:e.target.value})}/><Input label="MOBILE" value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/><label style={{fontSize:11,fontWeight:800}}>ROLE<select value={f.role} onChange={e=>setF({...f,role:e.target.value})} style={{width:"100%",padding:10,border:"1px solid #cbd7e7",borderRadius:9,marginTop:5}}>{roles.map(r=><option key={r} value={r}>{labels[r]}</option>)}</select></label><div style={{alignSelf:"end"}}><Btn type="submit">Create Account</Btn></div></form></Card><Card style={{marginTop:16}}><h2>Organization Structure</h2>{roles.map(r=><div key={r} style={{padding:"9px 0",borderBottom:"1px solid #e7edf5"}}><b>{labels[r]}</b><div style={{marginTop:5}}>{(r==="admin"?admins:rows.filter(x=>x.role===r)).map(x=><span key={x.id} style={{display:"inline-block",background:"#f7faff",border:"1px solid #dce5f2",borderRadius:8,padding:"7px 9px",margin:"4px 5px 0 0"}}>{x.name} <small>@{x.username}</small>{r==="admin"&&<button onClick={()=>toggle(x,!x.active)} style={{marginLeft:8,border:0,color:x.active?"#b42318":"#087443",background:"transparent",cursor:"pointer"}}>{x.active?"Disable":"Enable"}</button>}</span>)}{(r==="admin"?admins:rows.filter(x=>x.role===r)).length===0&&<span style={{color:"#8a98aa"}}>No accounts</span>}</div></div>)}</Card></>}
function Settings({setMsg}){const[s,setS]=useState(defaultSettings);useEffect(()=>{api("/ceo/settings").then(x=>setS({...defaultSettings,...x})).catch(e=>setMsg(e.message))},[]);const save=async e=>{e.preventDefault();try{await api("/ceo/settings",{method:"PATCH",body:JSON.stringify(s)});setMsg("CEO settings saved successfully.")}catch(e){setMsg(e.message)}};return <><h1>CEO System Settings</h1><p style={{color:"#6a7b93"}}>Edit whenever required. Changes are saved in the database.</p><Card><form onSubmit={save} style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{Object.entries(s).map(([k,v])=><Input key={k} label={k.replaceAll("_"," ").toUpperCase()} value={v} onChange={e=>setS({...s,[k]:e.target.value})}/>) }<div><Btn type="submit">Save Settings</Btn></div></form></Card></>}
function Permissions({setMsg}){const[all,setAll]=useState({});const[role,setRole]=useState("admin");const load=()=>api("/permissions").then(x=>setAll(x.permissions||{})).catch(e=>setMsg(e.message));useEffect(load,[]);const toggle=async(permission)=>{const allowed=!Boolean(all[role]?.[permission]);try{await api("/permissions",{method:"PATCH",body:JSON.stringify({role,permission,allowed})});setAll(x=>({...x,[role]:{...(x[role]||{}),[permission]:allowed}}))}catch(e){setMsg(e.message)}};return <><h1>Permissions</h1><p style={{color:"#6a7b93"}}>CEO controls exactly what each role can access.</p><Card><label style={{fontWeight:800}}>ROLE <select value={role} onChange={e=>setRole(e.target.value)} style={{marginLeft:8,padding:8,borderRadius:8}}>{roles.filter(r=>r!=="admin"||true).map(r=><option key={r}>{r}</option>)}</select></label>{permissionGroups.map(([g,items])=><div key={g} style={{marginTop:14}}><b>{g}</b>{items.map(([p,l])=><label key={p} style={{display:"block",padding:9,border:"1px solid #e7edf5",borderRadius:8,marginTop:5}}><input type="checkbox" checked={Boolean(all[role]?.[p])} onChange={()=>toggle(p)} style={{marginRight:8}}/>{l}</label>)}</div>)}</Card></>}
function SimpleList({title,path,fields}){const[data,setData]=useState([]);useEffect(()=>{api(path).then(x=>setData(Array.isArray(x)?x:[])).catch(()=>{})},[path]);return <><h1>{title}</h1><Card>{data.length?data.map(x=><div key={x.id||JSON.stringify(x)} style={{padding:10,borderBottom:"1px solid #e7edf5"}}><b>{x.name||x.customer_name||x.username||`#${x.id}`}</b><div style={{color:"#6a7b93",fontSize:12}}>{fields.map(k=>`${k}: ${x[k]??"—"}`).join(" · ")}</div></div>):<p style={{color:"#6a7b93"}}>No records available.</p>}</Card></>}
const Requests=()=> <SimpleList title="Requests" path="/requests" fields={["status","location","description","assigned_technician"]}/>;
const Customers=()=> <SimpleList title="Customers" path="/customers" fields={["phone","vehicle_no","address"]}/>;
const Technicians=()=> <SimpleList title="Technicians" path="/technicians" fields={["phone","specialization","active"]}/>;
const Payments=()=> <SimpleList title="Payments" path="/payments" fields={["amount","method","transaction_ref","paid_at"]}/>;
const Contact=()=> <Card><h1>Contact NRORA</h1><p>📞 9160264439</p><p>🌐 nrroadcare.in</p><p>📍 Telangana</p></Card>;
export default CeoApp;
