import React,{useEffect,useState}from"react";
import{Car,MapPin,UserRound,X,Camera,ArrowRight,Search,Loader2}from"lucide-react";
const empty={name:"",phone:"",house_number:"",landmark:"",state:"Telangana",district:"",mandal:"",village:"",pincode:"",referral_code:"",vehicle_no:"",vehicle_type:"",make_brand:"",model:"",variant:"",manufacturing_year:"",color:"",rc_number:"",photo1:"",photo2:""};
const districts=["Adilabad","Bhadradri Kothagudem","Hanamkonda","Hyderabad","Jagtial","Jangaon","Jayashankar Bhupalpally","Jogulamba Gadwal","Kamareddy","Karimnagar","Khammam","Kumuram Bheem","Mahabubabad","Mahabubnagar","Mancherial","Medak","Medchal-Malkajgiri","Mulugu","Nagarkurnool","Nalgonda","Narayanpet","Nirmal","Nizamabad","Peddapalli","Rajanna Sircilla","Rangareddy","Sangareddy","Siddipet","Suryapet","Vikarabad","Wanaparthy","Warangal","Yadadri Bhuvanagiri"];
const token=()=>localStorage.getItem("nrora_token")||localStorage.getItem("nrora_ceo_token");
const fileData=f=>new Promise((ok,no)=>{if(!f)return ok("");const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(f)});
const clean=v=>String(v||"").trim();
const uniq=a=>[...new Set(a.map(clean).filter(x=>x&&x.toUpperCase()!=="NA"))].sort((a,b)=>a.localeCompare(b));
export default function CustomerDetailsOverlay(){
 const[open,setOpen]=useState(false),[f,setF]=useState(empty),[err,setErr]=useState(""),[busy,setBusy]=useState(false),[show,setShow]=useState(false);
 const[mandals,setMandals]=useState([]),[villages,setVillages]=useState([]),[mandalSearch,setMandalSearch]=useState(""),[villageSearch,setVillageSearch]=useState(""),[geoBusy,setGeoBusy]=useState(false),[geoMsg,setGeoMsg]=useState("");
 useEffect(()=>{const c=()=>setShow(location.hash.startsWith("#/customers"));c();window.addEventListener("hashchange",c);return()=>window.removeEventListener("hashchange",c)},[]);
 const set=(k,v)=>setF(x=>({...x,[k]:v}));
 const loadMandals=async district=>{if(!district){setMandals([]);setVillages([]);return}setGeoBusy(true);setGeoMsg("");setMandals([]);setVillages([]);set("mandal","");set("village","");try{const where=`DISTRICT_NAME='${district.replace(/'/g,"''")}'`;const q=new URLSearchParams({where,outFields:"MANDAL_NAME,DISTRICT_NAME",returnGeometry:"false",f:"json"});const r=await fetch(`/api/telangana/mandals?${q.toString()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Mandal search failed (${r.status})`);const d=await r.json();const list=uniq((d.features||[]).map(x=>x.attributes?.MANDAL_NAME));if(!list.length)throw new Error("No mandals found for this district");setMandals(list);setGeoMsg(`${list.length} mandals loaded for ${district}.`)}catch(e){setGeoMsg(e.message||"Unable to load mandals")}finally{setGeoBusy(false)}};
 const loadVillages=async mandal=>{if(!f.district||!mandal){setVillages([]);set("village","");return}setGeoBusy(true);setGeoMsg("");setVillages([]);set("village","");try{const where=`DISTRICT_NAME='${f.district.replace(/'/g,"''")}' AND MANDAL_NAME='${mandal.replace(/'/g,"''")}'`;const q=new URLSearchParams({where,outFields:"VILLAGE_NAME,MANDAL_NAME,DISTRICT_NAME",returnGeometry:"false",f:"json",resultRecordCount:"2000"});const r=await fetch(`/api/telangana/villages?${q.toString()}`,{cache:"no-store"});if(!r.ok)throw new Error(`Village search failed (${r.status})`);const d=await r.json();const list=uniq((d.features||[]).map(x=>x.attributes?.VILLAGE_NAME));if(!list.length)throw new Error("No villages found for this mandal");setVillages(list);setGeoMsg(`${list.length} villages/towns loaded for ${mandal}.`)}catch(e){setGeoMsg(e.message||"Unable to load villages")}finally{setGeoBusy(false)}};
 const searchPin=async()=>{const pin=String(f.pincode||"").replace(/\D/g,"");set("pincode",pin);if(pin.length!==6){setGeoMsg("Enter a valid 6-digit PIN code");return}setGeoBusy(true);setGeoMsg("");try{const r=await fetch(`/api/pincode/${pin}`,{headers:{Accept:"application/json"},cache:"no-store"});if(!r.ok)throw new Error(`PIN search failed (${r.status})`);const d=await r.json(),root=Array.isArray(d)?d[0]:d,offices=Array.isArray(root?.PostOffice)?root.PostOffice:[];if(!offices.length)throw new Error(root?.Message||"PIN code not found");setGeoMsg(`${offices.length} post office(s) found. PIN verification completed.`)}catch(e){setGeoMsg(e.message||"PIN search failed")}finally{setGeoBusy(false)}};
 const save=async e=>{e.preventDefault();setErr("");if(!f.name||!/^[0-9]{10}$/.test(f.phone)||!f.vehicle_no||!/^[0-9]{6}$/.test(f.pincode)||!f.district||!f.mandal||!f.village){setErr("Name, mobile, vehicle number, PIN code, District, Mandal and Village/Town are required.");return}setBusy(true);try{const h={"Content-Type":"application/json",Authorization:`Bearer ${token()}`},b={...f,address:[f.house_number,f.landmark,f.district,f.mandal,f.village,f.pincode].filter(Boolean).join(", "),vehicle_no:f.vehicle_no.toUpperCase(),vehicle_photos:[f.photo1,f.photo2].filter(Boolean)};delete b.photo1;delete b.photo2;const r=await fetch("/api/customers",{method:"POST",headers:h,body:JSON.stringify(b)}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||"Unable to save customer");const id=d.id||d.customer?.id;if(id)await fetch("/api/customer-details",{method:"PATCH",headers:h,body:JSON.stringify({...b,customer_id:id})});setOpen(false);setF(empty);setMandals([]);setVillages([]);location.hash=`/payments?customer=${encodeURIComponent(id||"")}`}catch(e){setErr(e.message||"Unable to save customer")}finally{setBusy(false)}};
 const input={width:"100%",boxSizing:"border-box",padding:"10px 11px",border:"1px solid #cbd8e8",borderRadius:9,background:"#fff"},sel={...input,cursor:"pointer"};
 const field=(label,node)=><label style={{display:"grid",gap:5,fontSize:10,fontWeight:800,color:"#52677f"}}>{label}{node}</label>;
 if(!show)return null;
 return <><button type="button" onClick={()=>setOpen(true)} style={{position:"fixed",right:22,bottom:22,zIndex:300,border:0,borderRadius:13,padding:"13px 16px",background:"#1765e8",color:"#fff",fontWeight:800,boxShadow:"0 10px 30px rgba(23,101,232,.3)",cursor:"pointer",display:"flex",gap:8,alignItems:"center"}}><UserRound size={17}/> Full Customer Registration</button>{open&&<div style={{position:"fixed",inset:0,zIndex:500,background:"rgba(5,15,34,.68)",display:"grid",placeItems:"center",padding:18}}><div style={{width:"min(980px,100%)",maxHeight:"94vh",overflow:"auto",background:"#fff",borderRadius:18}}><div style={{position:"sticky",top:0,zIndex:2,padding:17,background:"linear-gradient(120deg,#0b2d5c,#1765e8)",color:"white",display:"flex",justifyContent:"space-between"}}><div><b>NRORA Full Customer Registration</b><div style={{fontSize:12,opacity:.85}}>Customer → Address → Vehicle → Documents → Payment</div></div><button type="button" onClick={()=>setOpen(false)} style={{border:0,background:"transparent",color:"white",cursor:"pointer"}}><X/></button></div><form onSubmit={save} style={{padding:20}}>
 <Section title="Customer Details" icon={<UserRound size={17}/>}><Grid>{field("FULL NAME *",<input required style={input} value={f.name} onChange={e=>set("name",e.target.value)}/>)}{field("MOBILE NUMBER *",<input required inputMode="numeric" maxLength="10" style={input} value={f.phone} onChange={e=>set("phone",e.target.value.replace(/\D/g,""))}/>)}{field("REFERRAL CODE",<input style={input} value={f.referral_code} onChange={e=>set("referral_code",e.target.value)}/>)}</Grid></Section>
 <Section title="Address" icon={<MapPin size={17}/>}><Grid>{field("HOUSE / DOOR NUMBER",<input style={input} value={f.house_number} onChange={e=>set("house_number",e.target.value)}/>)}{field("LANDMARK",<input style={input} value={f.landmark} onChange={e=>set("landmark",e.target.value)}/>)}{field("STATE",<select style={sel} value={f.state} onChange={e=>set("state",e.target.value)}><option>Telangana</option><option>Andhra Pradesh</option><option>Karnataka</option><option>Maharashtra</option><option>Tamil Nadu</option><option>Other</option></select>)}{field("DISTRICT *",<select required style={sel} value={f.district} onChange={e=>{set("district",e.target.value);loadMandals(e.target.value)}}><option value="">Select district</option>{districts.map(x=><option key={x}>{x}</option>)}</select>)}
 {field("MANDAL *",<select required disabled={!mandals.length} style={{...sel,opacity:mandals.length?1:.65}} value={f.mandal} onChange={e=>{set("mandal",e.target.value);loadVillages(e.target.value)}}><option value="">{mandals.length?"Select Mandal":"Select District first"}</option>{mandals.map(x=><option key={x}>{x}</option>)}</select>)}
 {field("VILLAGE / TOWN *",<select required disabled={!villages.length} style={{...sel,opacity:villages.length?1:.65}} value={f.village} onChange={e=>set("village",e.target.value)}><option value="">{villages.length?"Select Village / Town":"Select Mandal first"}</option>{villages.map(x=><option key={x}>{x}</option>)}</select>)}
 {field("PIN CODE *",<div style={{display:"flex",gap:7}}><input required inputMode="numeric" maxLength="6" style={{...input,flex:1}} value={f.pincode} onChange={e=>{set("pincode",e.target.value.replace(/\D/g,""));setGeoMsg("")}} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();searchPin()}}} placeholder="6-digit PIN"/><button type="button" onClick={searchPin} disabled={geoBusy} style={{border:0,borderRadius:9,padding:"0 13px",background:"#1765e8",color:"#fff",cursor:"pointer",display:"flex",alignItems:"center",gap:5}}>{geoBusy?<Loader2 size={17}/>:<Search size={17}/>} Search</button></div>)}</Grid>{geoMsg&&<div style={{marginTop:9,fontSize:11,fontWeight:700,color:/completed|found|loaded/i.test(geoMsg)?"#16803c":"#b42318"}}>{geoMsg}</div>}<div style={{marginTop:8,fontSize:10,color:"#6b7d93"}}>Select District → Mandal → Village/Town. PIN Search is only verification and does not decide the Mandal or Village.</div></Section>
 <Section title="Vehicle Details" icon={<Car size={17}/>}><Grid>{field("1. REGISTRATION NUMBER *",<input required style={input} value={f.vehicle_no} onChange={e=>set("vehicle_no",e.target.value.toUpperCase())} placeholder="TS09AB1234"/>)}{field("2. VEHICLE TYPE *",<select required style={sel} value={f.vehicle_type} onChange={e=>set("vehicle_type",e.target.value)}><option value="">Select vehicle type</option>{["Car","SUV","Hatchback","Sedan","MUV","Bike","Scooter","Auto","Commercial Vehicle","Truck","Bus","Other"].map(x=><option key={x}>{x}</option>)}</select>)}{field("3. MAKE / BRAND",<input style={input} value={f.make_brand} onChange={e=>set("make_brand",e.target.value)}/>)}{field("4. MODEL",<input style={input} value={f.model} onChange={e=>set("model",e.target.value)}/>)}{field("5. VARIANT",<input style={input} value={f.variant} onChange={e=>set("variant",e.target.value)}/>)}{field("6. MANUFACTURING YEAR",<input style={input} maxLength="4" value={f.manufacturing_year} onChange={e=>set("manufacturing_year",e.target.value.replace(/\D/g,""))}/>)}{field("7. COLOR",<input style={input} value={f.color} onChange={e=>set("color",e.target.value)}/>)}{field("8. RC NUMBER",<input style={input} value={f.rc_number} onChange={e=>set("rc_number",e.target.value)}/>)}</Grid></Section>
 <Section title="Vehicle Photos" icon={<Camera size={17}/>}><Grid>{field("VEHICLE PHOTO 1",<input type="file" accept="image/*" capture="environment" onChange={async e=>set("photo1",await fileData(e.target.files?.[0]))}/>)}{field("VEHICLE PHOTO 2",<input type="file" accept="image/*" capture="environment" onChange={async e=>set("photo2",await fileData(e.target.files?.[0]))}/>)}</Grid></Section>
 {err&&<div style={{background:"#fff0f0",color:"#b42318",padding:11,borderRadius:9,marginBottom:12}}>{err}</div>}<div style={{display:"flex",justifyContent:"flex-end",gap:8}}><button type="button" onClick={()=>setOpen(false)} style={{padding:"11px 16px",border:0,borderRadius:9,cursor:"pointer"}}>Cancel</button><button type="submit" disabled={busy} style={{padding:"11px 16px",border:0,borderRadius:9,background:"#1765e8",color:"white",fontWeight:800,cursor:"pointer",display:"flex",gap:7,alignItems:"center"}}>{busy?"Saving…":"Save & Continue to Payment"}<ArrowRight size={16}/></button></div></form></div></div>}</>}
function Section({title,icon,children}){return <section style={{border:"1px solid #e1e9f3",borderRadius:14,padding:15,marginBottom:13,background:"#f9fbff"}}><h3 style={{margin:"0 0 11px",fontSize:15,color:"#14345d",display:"flex",gap:7,alignItems:"center"}}>{icon}{title}</h3>{children}</section>}
function Grid({children}){return <div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:10}}>{children}</div>}
